# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Drone_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(20, 10, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(20, 120, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Stop.setFont(font)
        self.Stop.setObjectName("Stop")
        self.ReturnHome = QtWidgets.QPushButton(self.centralwidget)
        self.ReturnHome.setGeometry(QtCore.QRect(20, 230, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ReturnHome.setFont(font)
        self.ReturnHome.setObjectName("ReturnHome")
        self.HeightControl = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.HeightControl.setGeometry(QtCore.QRect(250, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.HeightControl.setFont(font)
        self.HeightControl.setMinimum(0.25)
        self.HeightControl.setMaximum(5.0)
        self.HeightControl.setSingleStep(0.05)
        self.HeightControl.setProperty("value", 0.25)
        self.HeightControl.setObjectName("HeightControl")
        self.HieghtLabel = QtWidgets.QLabel(self.centralwidget)
        self.HieghtLabel.setGeometry(QtCore.QRect(250, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.HieghtLabel.setFont(font)
        self.HieghtLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HieghtLabel.setAutoFillBackground(False)
        self.HieghtLabel.setObjectName("HieghtLabel")
        self.TreeSelect = QtWidgets.QSpinBox(self.centralwidget)
        self.TreeSelect.setGeometry(QtCore.QRect(220, 150, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TreeSelect.setFont(font)
        self.TreeSelect.setSuffix("")
        self.TreeSelect.setMinimum(1)
        self.TreeSelect.setMaximum(18)
        self.TreeSelect.setObjectName("TreeSelect")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 280, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Drone Controller"))
        self.Start.setText(_translate("MainWindow", "Start Drone"))
        self.Stop.setText(_translate("MainWindow", "Stop Drone"))
        self.ReturnHome.setText(_translate("MainWindow", "Return Home"))
        self.HeightControl.setSuffix(_translate("MainWindow", " m"))
        self.HieghtLabel.setText(_translate("MainWindow", "Flight Height"))
        self.TreeSelect.setPrefix(_translate("MainWindow", "Select Tree: "))
        self.pushButton.setText(_translate("MainWindow", "Get Width"))
        self.label.setText(_translate("MainWindow", "Width: --"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
